cache:
  directories:
      - node_modules
      # Cache directory for older Composer versions.
      - $HOME/.composer/cache/files
      # Cache directory for more recent Composer versions.
      - $HOME/.cache/composer/files

language:
  - php
  - node_js

node_js:
  - '10'

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - '7.4snapshot'

matrix:
  fast_finish: true
  include:
      - php: 7.3
        env: PHPCS=1

allow_failures:
  # Allow failures for unstable builds.
  - php: '7.4snapshot'

before_install:
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

  - composer install
  - npm install

script:
  # Validate the composer.json file.
  # @link https://getcomposer.org/doc/03-cli.md#validate
  - composer validate --no-check-all --strict

  # Lint the PHP files against parse errors.
  - composer lint

jobs:
  include:
      - stage: 'Tests fresh package versions'
        name: Tests
        script:
            # Run the theme through lint:pkg-json checker as defined in @wordpress/scripts package.
            - npm run lint:pkg-json

            # Run the theme through check-licenses checker as defined in @wordpress/scripts package.
            - npm run check-licenses
      - stage: 'Release'
        name: Release build
        if: branch = develop
        script:
            - node ./deploy/patch-version.js
            - npm run build
            - cd ./gutenberg
            - npm i
            - npm run build
        deploy:
            provider: pages
            skip_cleanup: true
            github_token: $GITHUB_OAUTH_TOKEN
            target_branch: pre-master
            on:
                branch: develop