dist: trusty

cache:
    directories:
        # Cache directory for older Composer versions.
        - $HOME/.composer/cache/files
        # Cache directory for more recent Composer versions.
        - $HOME/.cache/composer/files
        - node_modules

language:
    - php
    - node_js

node_js:
    - '10'

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - '7.4snapshot'

matrix:
    fast_finish: true
    include:
        - php: 7.3

allow_failures:
    # Allow failures for unstable builds.
    - php: '7.4snapshot'

before_install:
    # Speed up build time by disabling Xdebug.
    # @link https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
    # @link https://twitter.com/kelunik/status/954242454676475904
    - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

    - composer install
    - npm install

script:
    # Validate the composer.json file.
    # @link https://getcomposer.org/doc/03-cli.md#validate
    - composer validate --no-check-all --strict

    # Lint the PHP files against parse errors.
    - composer lint

    # Check the code against the standards as documented in the phpcs.xml.dist file.
    # - if [[ "$PHPCS" == 1 ]]; then composer checkcs; fi

    # Run the theme through lint:js checker as defined in @wordpress/scripts package.
    # - if [[ "$PHPCS" == 1 ]]; then npm run lint:js; fi

    # # Run the theme through lint:css checker as defined in @wordpress/scripts package.
    # - if [[ "$PHPCS" == 1 ]]; then npm run lint:css; fi

    # Run the theme through lint:pkg-json checker as defined in @wordpress/scripts package.
    - if [[ "$PHPCS" == 1 ]]; then npm run lint:pkg-json; fi

jobs:
    include:
        - stage:
          name: build
          if: branch = develop
          # install:
          #     - rm -rf .git
          #     - git clone -b develop https://github.com/mindbox-moscow/ui-kit.git
          #     - npm install

          script:
              - npm run build

          # deploy:
          #     provider: npm
          #     skip_cleanup: true
          #     email: $NPM_EMAIL_ADDRESS
          #     api_key: $NPM_AUTH_TOKEN
          #     on:
          #         branch: develop

          after_script:
              - git config --global user.email "travis@travis-ci.org"
              - git config --global user.name "Travis CI"
              - git add --all
              - 'git commit --message "📝 Update bundles $TRAVIS_BUILD_NUMBER"'
              - git push "https://${GITHUB_TOKEN}@github.com/ivannikitin-com/lustshop"
