# This is a basic workflow to help you get started with Actions

name: Deploy_Test_Server
on: 
  push:
    branches: develop

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout  
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      
    - name: Build
      run: npm run build
      
  deploy:  
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_TEST_KEY}}
      with:
        flags: '-avzr --delete'
        options: '--exclude="postcss.config.js" --exclude="webpack.config.js"'
        ssh_options: '-p 99999'
        src: '.'
        dest: 'vadim@wp-server.ru:/www/lustshop/www/wp-content/themes/lustshop'
      
