# This is a basic workflow to help you get started with Actions

name: Pull Request

on: 
  push:
    branches: develop

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout  
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      
    - name: Get old version
      run: |
        npm i
        git clone -b pre-master https://github.com/ivannikitin-com/lustshop.git old-version

    - name: Update version
      run: node deploy/update-version.js
      
    - name: Remove folder old-varsion
      run: rm -rf old-version
      
    - name: Build
      run: npm run build
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUD_TOKEN }}
        publish_branch: pre-master
        publish_dir: .
        keep_files: true
      
